In [1]:
import sys
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '1'
sys.path.append('/data/nas-gpu/wang/atong/SMART-Moonshot')
from api import get_api
api = get_api()


2026-03-10 22:34:53,569 - modules.core.const - INFO - Detected yuzu setup
2026-03-10 22:34:54,782 - modules.data.fp_loader - INFO - Loaded precomputed feature map (16384 features) from /data/nas-gpu/wang/atong/Datasets/MARINABase1/RankingEntropy/bitinfo_to_idx.pkl
2026-03-10 22:34:54,782 - modules.marina.model - INFO - [MARINA] Started Initializing
2026-03-10 22:34:55,350 - modules.marina.model - INFO - [MARINA] Initialized
2026-03-10 22:34:56,730 - modules.core.ranker - INFO - [RankingSet] Initialized with 518901 sample(s); metric=cosine


/data/nas-gpu/wang/atong/SMART-Moonshot/.pixi/envs/default/lib/python3.13/site-packages/torch/_utils.py:360: UserWarning: Sparse CSR tensor support is in beta state. If you miss a functionality in the sparse tensor support, please submit a feature request to https://github.com/pytorch/pytorch/issues. (Triggered internally at /pytorch/aten/src/ATen/SparseCsrTensorImpl.cpp:53.)
  result = torch.sparse_compressed_tensor(


In [2]:
api.fp_loader.build_mfp(1)

FileNotFoundError: Missing FragIdx shard: /data/nas-gpu/wang/atong/Datasets/MARINABase1/arrow/train/FragIdx.parquet

In [2]:
results, stats = api.benchmark_all()
stats

100%|██████████| 154/154 [00:12<00:00, 12.35it/s]


{'top_1_accuracy': 0.14935064935064934,
 'top_5_accuracy': 0.3116883116883117,
 'top_10_accuracy': 0.42857142857142855,
 'mean_cosine_sim': 0.5470137872866222}

In [4]:
for data in api.benchmark_data.values():
    if api.smiles_search(data['smiles'])['retrievals'][0]['cosine_sim'] < 1 - 1e-6:
        print(data['npid'])

NP0332808


In [5]:
api.smiles_search('CCC(C)C1NC(=O)C(Cc2c[nH]c3ccccc23)NC(=O)C2CCCN2C(=O)C2CSSCC(C(=O)NC(CC(C)C)C(=O)O)NC(=O)C(CSSCC(NC(=O)C(N)CO)C(=O)N2)NC(=O)C(Cc2c[nH]c3ccccc23)NC(=O)C(C(C)CC)NC1=O')

{'retrievals': [{'cosine_sim': 0.8477316498756409,
   'tanimoto_sim': tensor(0.7353),
   'smiles': 'CCC(C)C1NC(=O)C(Cc2c[nH]c3ccccc23)NC(=O)C2CCCN2C(=O)C(N)CSSCC2NC(=O)C(CSSCC(C(=O)O)NC(=O)C(CO)NC(=O)C(CC(C)C)NC2=O)NC(=O)C(Cc2c[nH]c3ccccc23)NC(=O)C(C(C)CC)NC1=O',
   'retrieval_idx': 499839},
  {'cosine_sim': 0.7508008480072021,
   'tanimoto_sim': tensor(0.5971),
   'smiles': 'CCC(C)C1NC(=O)C(C(C)CC)NC(=O)C2CCCN2C(=O)C(CC(N)=O)NC(=O)C(Cc2c[nH]c3ccccc23)NC(=O)C(C(C)CC)NC(=O)C2CCCN2C(=O)CNC1=O',
   'retrieval_idx': 231327},
  {'cosine_sim': 0.7387488484382629,
   'tanimoto_sim': tensor(0.5850),
   'smiles': 'CCC(C)C1NC(=O)C(CC(C)C)NC(=O)C2CCCN2C(=O)C(CC(N)=O)NC(=O)C(Cc2c[nH]c3ccccc23)NC(=O)C(C(C)CC)NC(=O)C2CCCN2C(=O)CNC1=O',
   'retrieval_idx': 471378},
  {'cosine_sim': 0.7237129211425781,
   'tanimoto_sim': tensor(0.5612),
   'smiles': 'CCC(C)C1NC(=O)C(CC(C)C)NC(=O)C2CCCN2C(=O)C(C(C)C)NC(=O)C(Cc2c[nH]c3ccccc23)NC(=O)C2CCCN2C(=O)C(C(C)CC)NC(=O)C2CCCN2C1=O',
   'retrieval_idx': 317905},
  

In [6]:
import torch
torch.nonzero(api.get_fp_for_smiles('CCC(C)C1NC(=O)C(Cc2c[nH]c3ccccc23)NC(=O)C2CCCN2C(=O)C2CSSCC(C(=O)NC(CC(C)C)C(=O)O)NC(=O)C(CSSCC(NC(=O)C(N)CO)C(=O)N2)NC(=O)C(Cc2c[nH]c3ccccc23)NC(=O)C(C(C)CC)NC1=O') > 0).reshape(-1)

tensor([    1,     2,     4,     5,     6,     8,    10,    11,    12,    13,
           14,    19,    20,    21,    22,    24,    25,    29,    30,    34,
           36,    42,    45,    46,    50,    62,    74,   131,   156,   173,
          205,   206,   220,   233,   265,   266,   285,   287,   293,   308,
          316,   325,   326,   336,   353,   356,   365,   385,   411,   425,
          458,   465,   481,   517,   535,   546,   609,   619,   679,   690,
          720,   734,   821,   830,   867,   868,   875,   910,   950,  1026,
         1034,  1054,  1070,  1125,  1132,  1166,  1206,  1219,  1380,  1403,
         1626,  1716,  1720,  1782,  1815,  1955,  2037,  2403,  2615,  2693,
         2808,  2895,  3082,  3228,  3611,  3662,  4043,  4212,  4531,  4892,
         5272,  5292,  5681,  5686,  6009,  7379,  7678,  7716,  7757,  7762,
         7870,  8132,  8140,  9002, 10393, 10470, 11711, 12014, 13657, 14996,
        16345])

In [24]:
fp1 = api.get_fp_for_smiles('COc1c2c(c(OC)c(O)c1-c1c[nH]c3ccccc13)C1(O)c3ccccc3NC1O2') > 0
fp2 = api.model.ranker.data[35406].float().to_dense()
torch.nn.functional.cosine_similarity(fp1, fp2, dim=0).item()

0.9787234663963318

In [26]:
torch.nonzero(fp2 > 0).reshape(-1)

tensor([    0,     1,     3,     5,     6,     7,    12,    15,    19,    22,
           23,    29,    36,    38,    46,    50,    59,    63,    84,   126,
          173,   202,   205,   209,   217,   220,   285,   308,   326,   354,
          358,   368,   545,   598,   603,   610,   722,   724,   790,   920,
         1059,  1202,  4339,  8584,  9061,  9761, 12267])

In [30]:
torch.nonzero(fp1 > 0).reshape(-1)

tensor([    0,     1,     3,     5,     6,     7,    12,    15,    19,    22,
           23,    29,    36,    38,    46,    50,    59,    63,    84,   126,
          173,   202,   205,   209,   217,   220,   285,   308,   326,   354,
          358,   368,   545,   549,   603,   610,   722,   724,   790,   920,
         1059,  1202,  4339,  8584,  9061,  9761, 12267])